<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="/Users/gyliang/Android Application Test/src/main/resources"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="40.853">
  <properties />
            <testcase name="RunLoginOut" time="25.925" classname="com.aiways.cases.androidapplicationtest.logincases.LoginOutCases">
                <failure type="java.lang.AssertionError"
                  message="当前已退出登录 expected [true] but found [false]"
              >
                    <![CDATA[java.lang.AssertionError: 当前已退出登录 expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:96)
  org.testng.Assert.failNotEquals(Assert.java:776)
  org.testng.Assert.assertTrue(Assert.java:44)
  com.aiways.Invokers.androidInvokers.LoginInvoker.loginOut(LoginInvoker.java:97)
  com.aiways.cases.androidapplicationtest.logincases.LoginOutCases.RunLoginOut(LoginOutCases.java:45)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
  org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:175)
  org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
                </failure>

          </testcase>
  
  
            <testcase name="RunLoginOut" time="14.928" classname="com.aiways.cases.androidapplicationtest.logincases.LoginOutCases" />
      
</testsuite>
